id: d27b909027d1487889e5167d580410fc
initial_creation_type: ocr
source_metadata:
  volumes:
    0ac3a6ed8e3b47b5af2b63b1fdcd808f:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
